-- CreateTable
CREATE TABLE `TimeOff` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `startDate` DATETIME(3) NOT NULL,
    `endDate` DATETIME(3) NOT NULL,
    `timeOffType` ENUM('CONGE_PAYE', 'CONGE_MALADIE', 'CONGE_SANS_SOLDE', 'CONGE_PARENTAL') NOT NULL,
    `status` ENUM('EN_ATTENTE', 'APPROUVE', 'REFUSE') NOT NULL DEFAULT 'EN_ATTENTE',
    `employeeId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
